#ifndef CONSTANTS_H
#define CONSTANTS_H

unsigned int MAX_DISTANCE = 100;  //Centimeters
int SERIAL_FREQ = 9600;
int VERY_SHORT_DISTANCE_THRESHOLD = 60;
int SHORT_DISTANCE_THRESHOLD = 30;
int FALSE_READ_THRESHOLD = 5;
int SERVO_LEFT_ANGLE = 170; 
int SERVO_RIGHT_ANGLE = 10;
int SERVO_CENTER_ANGLE = 90;
int FAST_DELAY = 10;
int NORMAL_DELAY = 200;
int MEASURES_BORING = 15;

#endif